name: Deploy to AWS Lambda (Serverless Framework)

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Run only if it's a push to main or dev
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies without dev
        run: npm install --omit=dev

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Serverless Warmup Plugin
        run: npm install --save-dev serverless-plugin-warmup

      - name: Set environment variables
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "STAGE=prod" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_ENV
            echo "AWS_BUCKET_NAME=${{ vars.AWS_BUCKET_NAME_PROD }}" >> $GITHUB_ENV
            echo "AWS_BUCKET_URL=${{ vars.AWS_BUCKET_URL_PROD }}" >> $GITHUB_ENV
            echo "AWS_CLOUDFRONT_URL=${{ vars.AWS_CLOUDFRONT_URL_PROD }}" >> $GITHUB_ENV
            echo "MONGODB_URI=${{ vars.MONGODB_URI_PROD }}" >> $GITHUB_ENV
            echo "SMTP_HOST=${{ vars.SMTP_HOST_PROD }}" >> $GITHUB_ENV
            echo "SMTP_PORT=${{ vars.SMTP_PORT_PROD }}" >> $GITHUB_ENV
            echo "SMTP_USER=${{ vars.SMTP_USER_PROD }}" >> $GITHUB_ENV
            echo "SMTP_PASSWORD=${{ vars.SMTP_PASSWORD_PROD }}" >> $GITHUB_ENV
            echo "FRONTEND_URL=${{ vars.FRONTEND_URL_PROD }}" >> $GITHUB_ENV
            echo "COOKIE_DOMAIN=${{ vars.COOKIE_DOMAIN_PROD }}" >> $GITHUB_ENV
          else
            echo "STAGE=dev" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "AWS_BUCKET_NAME=${{ vars.AWS_BUCKET_NAME }}" >> $GITHUB_ENV
            echo "AWS_BUCKET_URL=${{ vars.AWS_BUCKET_URL }}" >> $GITHUB_ENV
            echo "AWS_CLOUDFRONT_URL=${{ vars.AWS_CLOUDFRONT_URL }}" >> $GITHUB_ENV
            echo "MONGODB_URI=${{ vars.MONGODB_URI }}" >> $GITHUB_ENV
            echo "SMTP_HOST=${{ vars.SMTP_HOST }}" >> $GITHUB_ENV
            echo "SMTP_PORT=${{ vars.SMTP_PORT }}" >> $GITHUB_ENV
            echo "SMTP_USER=${{ vars.SMTP_USER }}" >> $GITHUB_ENV
            echo "SMTP_PASSWORD=${{ vars.SMTP_PASSWORD }}" >> $GITHUB_ENV
            echo "FRONTEND_URL=${{ vars.FRONTEND_URL }}" >> $GITHUB_ENV
            echo "COOKIE_DOMAIN=${{ vars.COOKIE_DOMAIN }}" >> $GITHUB_ENV
          fi
          echo "AWS_REGION=${{ vars.AWS_REGION }}" >> $GITHUB_ENV

          # Application Environment Variables

          echo "PORT=${{ vars.PORT }}" >> $GITHUB_ENV
          echo "NODE_ENV=${{ vars.NODE_ENV }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ vars.JWT_SECRET }}" >> $GITHUB_ENV
          echo "JWT_REFRESH_SECRET=${{ vars.JWT_REFRESH_SECRET }}" >> $GITHUB_ENV
          echo "JWT_EXPIRES=${{ vars.JWT_EXPIRES }}" >> $GITHUB_ENV
          echo "COOKIE_EXPIRES=${{ vars.COOKIE_EXPIRES }}" >> $GITHUB_ENV
          echo "CORS_ORIGINS=${{ vars.CORS_ORIGINS }}" >> $GITHUB_ENV
          echo "LOGO_URL=${{ vars.LOGO_URL }}" >> $GITHUB_ENV
          echo "HOSPITAL_NAME=${{ vars.HOSPITAL_NAME }}" >> $GITHUB_ENV
          echo "SERVERLESS_ACCESS_KEY=${{ vars.SERVERLESS_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy with Serverless
        run: sls deploy --stage ${{ env.STAGE }}
